### ISSUE TITLE
Question about the philosophy you promote for JS OOP

### ISSUE THREAD

**Issue by romankolpak** [learn-javascript-courses/javascript-questions#13]
Hi!

In your articles (which I find great and influencing many developers by the way) you often state that `new` keyword is evil, classes are not needed and all we need to use to be happy is your `stampit` library. 
The ideas seem reasonable, but my concern is that I don't see software written following those ideas ever in my day-to-day practice. 

Maybe I was looking in wrong places, but it seems that most of the JavaScript development world relies on "classes". And software we use everyday is exposing it's API as classes. Think of Backbone or RxJS as an example. 

I think on one of your Medium articles you mentioned jQuery as an example, but I don't think it's an appropriate example for most of us -- jQuery is basically a collection of helper functions to help you work with DOM. 

What I'd like to see as an example is a project closer to things we build for production -- eshops, crm, cms, utility apps, social apps -- anything that looks like a real world app and follows your ideas.

Or maybe a library that has a larger API surface and exposes a number of entities. Think of Backbone exposing things classes like Backbone.Controller, Backbone.Controller etc.

Thanks.

**Comment by ericelliott** [comment]
> I don't see software written following those ideas ever in my day-to-day practice.

Unless you started writing JavaScript yesterday, I don't believe that's true. You see examples of concatenative inheritance and delegation everywhere. There are examples of factories (as opposed to constructors) everywhere, too.

See [Common Misconceptions About Inheritance in JavaScript](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a), specifically the sections labelled "The Native APIs use Constructors. Aren’t they More Idiomatic than Factories?" & "Isn’t Classical Inheritance More Idiomatic than Prototypal Inheritance?"

This list is particularly relevant to your question:

## What else exposes factories?

* React `React.createClass()` is a factory.
* Angular uses classes & factories, but wraps them all with a factory in the Dependency Injection container. All providers are sugar that use the `.provider()` factory. There’s even a `.factory()` provider, and even the `.service()` provider wraps normal constructors and exposes … you guessed it: A factory for DI consumers.
* Ember `Ember.Application.create();` is a factory that produces the app. Rather than creating constructors to call with `new`, the `.extend()` methods augment the app.
* Node core services like `http.createServer()` and `net.createServer()` are factory functions.
* Express is a factory that creates an express app.

Speaking of Backbone, an example **from the Backbone docs** showing concatenative inheritance:

```js
var object = {};

_.extend(object, Backbone.Events);

object.on("alert", function(msg) {
  alert("Triggered " + msg);
});

object.trigger("alert", "an event");
```

The `$.extend()` and `_.extend()` functions for concatenative inheritance were so popular, they got added to the JavaScript specification as `Object.assign()`.

> you mentioned jQuery as an example, but I don't think it's an appropriate example for most of us -- jQuery is basically a collection of helper functions to help you work with DOM.

I'm not sure why you would assert that the most commonly used and well-known JavaScript library in the world by a HUGE margin is not a good example to point out the popularity of the techniques. On the contrary, it shows that the techniques are so commonly encountered in the JavaScript most people read and write every day that JavaScript developers take them for granted. They're so thoroughly pervasive as to be almost invisible to people who don't understand what they're looking for.

> "Inheritance in JS is so easy
it confuses people who expect it to take effort.
> To make it harder, we added `class`."
