### ISSUE TITLE
How do you write unit tests for interactive command line applications?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#19]
I have this command line application called [timecard](https://github.com/radiovisual/timecard), which helps me keep track of my project development time. 

I have written [unit tests](https://github.com/radiovisual/timecard/blob/master/test/test.js) for my application, but I am unable to get 100% test coverage, because I have only been able to test the API of my application, and not the cli portion of the app. 

Can you help point me in the right direction, show me some code samples or describe the basic methodologies involved in testing interactive command line applications? Testing command line applications that simply output something to the console is easy, what I need is help with is testing interactive applications that ask the user for input, and uses that input to decide what to do next. 

My application is using inquirer.js, so the calls I am trying to test are based off [`inquier.prompt()`](https://github.com/radiovisual/timecard/blob/master/lib/index.js#L50). 

Do have any advice for something like this? I would appreciate any advice you can offer. 

Thanks!

**Comment by ericelliott** [comment]
Unit tests should not test *everything* in your app -- only the public API of your app's modules. That's why they're called unit tests, because they focus on the individual units of the application.

What you need in order to reach 100% coverage are **functional tests**.

The way you use functional tests varies depending on how your application receives I/O. For example, web applications can use browser testing APIs like Selenium/WebDriver.

For simple CLI tools, you can call the CLI with specific arguments, and write tests against the text that gets logged to the console.

For more complicated curses-style interfaces, I'm not sure what options are available for simulating user input. Perhaps there's some way you can fake it by hijacking stdin.

Good luck!

**Comment by radiovisual** [comment]
> Perhaps there's some way you can fake it by hijacking stdin.

Alright, cool. I will start experimenting with this as my starting point. 

Thanks!

:+1:

**Comment by ericelliott** [comment]
:+1:
