### ISSUE TITLE
Where can I find example source code for apps written with great functional programming principles in javascript? 

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#2]
I am new to the functional programing paradigm, and it has me very excited to learn all I can about the subject (and to start using these new patterns in my own applications). The problem I am facing right now is that I don't know where to look when I want to study code written with these design patterns. I am hoping that you can help point out a few **large** open-source projects that use functional programing principles so that I can start to learn more about their application architecture (meaning: how do they organize their files, how do the developers think about / plan out their objects and keep them organized in a way that makes the large application maintainable, etc).

The examples that I have seen so far are all very small examples, used mainly to demonstrate a proof of concept, like the one you talk about in your video [Classical Inheritance is Obsolete - How to Think in Prototypal OO](http://vimeo.com/69255635):

    var proto = {
        hello: function hello() {
            return 'Hello, my name is ' + this.name;
        }
    };
    var george = Object.create(proto);
    george.name = "George";

This example is great, but I am wondering how large applications keep their "prototype" objects organized without things getting out of control and losing track of the various "pieces of the puzzle."

I imagine a scenario where applications are made up of puzzle pieces, and each puzzle piece is made up of smaller pieces, and those pieces are made up of even smaller pieces....so the thought of organizing all those random pieces seems like it could be tricky for large applications. So I would love to see these principles in the wild.

**Comment by ericelliott** [comment]
First, based on your example, it sounds like you're talking about prototypal inheritance, not functional programming. They're very different paradigms. I consider them complementary. See [The Two Pillars of JavaScript Pt 1](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3) for prototypal inheritance, and [The Two Pillars of JavaScript Pt 2](https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4) for functional programming.

As for prototypal inheritance examples, that's easy. Every app that makes heavy use of jQuery is also making heavy use of prototypal inheritance. Why? Almost every time you call the jQuery function (`jQuery()` or `$()`), you're creating a new `jQuery` object. jQuery (along with every jQuery plugin) adds methods to it's prototype by attaching to `jQuery.fn` (concatenative inheritance). Every instance of the jQuery object then delegates to `jQuery.fn` (Objects Linking to Other Objects, aka OLOO, differential inheritance). Both of those things are forms of prototypal inheritance.

Every time you see something calling `$.extend()` or `_.extend()`, that's an example of concatenative inheritance. Every time you see something adding methods to a prototype, e.g. `Foo.prototype.myMethod = someFn;`, that's an example of OLOO / differential inheritance.

These concepts are used all the time in JavaScript. I've never seen an app that *didn't* make heavy use of them. That's why I was so disappointed when Backbone.js trumpeted the mainstream acceptance of class-based OO styles in modern JavaScript apps.

**We already had support for amazing inheritance in JS.** People used it and didn't even realize they were doing inheritance. It was so good, it was **completely transparent** to the users. But that confused people who were accustomed to inheritance that took *work* and *effort* and *thought.*

My assertion is that the *work* and *effort* and *thought* required by classical OO is like putting speed bumps on the freeway. Completely counter to the goal of getting to your destination quickly.

**Comment by radiovisual** [comment]
Wow. Thank you so much for such a detailed explanation. I really learned a lot. I really appreciate it! This brought to mind a few follow up questions, which I will stage as new questions, making these questions easier to find and reference for myself and others. Again, I really appreciate the time you put into this response. You are one seriously knowledgeable guy, and it's awesome that you are willing to help others in the way that you do. I am excited for your video courses!

**Comment by ericelliott** [comment]
:+1:

**Comment by djindjic** [comment]
Hello @ericelliott, I follow you on twitter and very like you posts. I'm specially interested in term of, like you said 'classical inheritance is obsolete'. I can say that I understand prototypical inheritance (for example) like it is shown in popular sample:

```js
var proto = {
    hello: function hello() {
        return 'Hello, my name is ' + this.name;
    }
};
var george = Object.create(proto);
george.name = "George";
```

but I cant find any simple, few line, code sample of classical inheritance in javascript to clear this differences to myself. Could you paste it us here?

**Comment by warren2k** [comment]
Here's an example in the classical inheritance style, with a subsequent call to the `hello()` method:

```javascript
function Greeter() {

    this.name = '';

    this.hello = function hello() {
        return 'Hello, my name is ' + this.name;
    }
}

var george = new Greeter();
george.name = 'George';
george.hello();
```
