### ISSUE TITLE
Is functional javascript programming the answer?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#8]
From my understanding of functional programming paradigms so far, there are major differences to the imperative programming paradigms. Functional programming introduces concepts such as currying, partially-applied functions, type inference, lazy evaluation, "statelessness", etc...

In order to re-structure their way of thinking about problem solving and application design, developers who have a background in imperative languages will be forced to exercise a literal "paradigm shift", given the fact that functional structures are vastly different than imperative structures. 

So my questions for you are:

###1. Can functional programming solve all the same problems that imperative programming can? 
Meaning: are functional-programming paradigms best suited to solve specific types of problems (like a design pattern), or is functional-programming capable of being "the one" paradigm, where all problems can be solved in a functional way? 

I suppose my question stems from this notion of stateless functions, or wrapping my head around this idea of "stateless problem solving", specifically in the context of web development, where so much seems to be tied to some sort of state (is the user logged in? can the user perform certain actions? are we in mode X? or mode Y? has the page loaded? are we waiting for a resource to load? etc...), which leads me to a follow up question:

###2. Is functional programming appropriate for front-end development?
It seems that front-end development uses "state" quite a bit, so if you want to use functional programming, will it end up being more work than its worth to think without state? or once you master the functional paradigm, can it be applied equally on the front-end and the back-end? Or would it be more realistic (in the context of web development) to use a majority of functional programming techniques where you can, and then mix in a bit of imperative styles to write a complete program?

**Comment by ericelliott** [comment]
> Can functional programming solve all the same problems that imperative programming can? 
Meaning: are functional-programming paradigms best suited to solve specific types of problems (like a design pattern), or is functional-programming capable of being "the one" paradigm, where all problems can be solved in a functional way?

There "pure" functional languages where imperative programming is not supported at all. In some of them, assignment statements are not even possible. In other words, everything in the program is a pure function, including the whole program itself. Alonzo Church proved in the 1930's that anything that is computable can be computed with lambda functions.

> Is functional programming appropriate for front-end development?

I use it frequently for front-end development. Note that statelessness is a hallmark of the REST architectural style, where state is transmitted by state representations that can be used as the inputs and outputs of pure functions. In fact, REST stands for "Representational State Transfer" for exactly that reason.

That said, I mix functional programming and prototypal OO liberally, and I consider them complementary paradigms, which is why together, they make up [The Two Pillars](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3) [of JavaScript](https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4).

**Comment by radiovisual** [comment]
:+1:
